using Enum = Loom.TypeGenerator.ApiTypes.Enum;

namespace Loom.TypeGenerator.Generators;

internal class EnumGenerator(string filePath, ReflectionMetadataReader metadata)
    : Generator(filePath, metadata)
{
    public void Generate(Enum[] enums)
    {
        WriteAutoGeneratedHeader();
        Write("## Generated Roblox enums");
        Write();
        WriteBlock(
            "declare interface EnumItem",
            () =>
            {
                Write("Name: string");
                Write("Value: number");
                Write("EnumType: never");
            }
        );

        var enumNames = new List<string>();
        for (var i = 0; i < enums.Length; i++)
        {
            var rbxEnum = enums[i];
            enumNames.Add(rbxEnum.Name);
            GenerateEnum(rbxEnum, i == enums.Length - 1);
        }

        WriteBlock("declare interface Enum", () => WriteList(enumNames, name => $"{name}: {name};"));
        Write("declare let Enum: Enum;");
        WriteFile();
    }
    
    private void GenerateEnum(Enum rbxEnum, bool isLast) =>
        WriteBlock($"declare interface {rbxEnum.Name}", () => WriteList(rbxEnum.Items, item => $"{item.Name}: EnumItem;"), !isLast);
}