using System.Text;

namespace Loom.TypeGenerator.Generators;

internal abstract class Generator(string filePath, ReflectionMetadataReader? metadata = null)
{
    protected readonly ReflectionMetadataReader? Metadata = metadata;

    private readonly MemoryStream _stream = new();
    private string _indent = string.Empty;

    protected void WriteFile()
    {
        Directory.CreateDirectory(Path.GetDirectoryName(filePath)!);
        File.WriteAllText(filePath, GetStringFromMemoryStream());
    }

    protected void WriteBlock(string header, Action writeBlock, bool finalNewline = true)
    {
        Write(header + " {");
        PushIndent();
        writeBlock();
        PopIndent();
        Write("}");

        if (!finalNewline) return;
        Write();
    }

    protected void WriteAutoGeneratedHeader() => Write("## This is an automatically generated file and it should not be edited manually.");
    protected void WriteList<T>(IEnumerable<T> enumerable, Func<T, string> renderElement) => enumerable.Select(renderElement).ToList().ForEach(Write);
    protected void Write() => Write("");
    protected void Write(string line) => _stream.Write(Encoding.UTF8.GetBytes($"{_indent}{line}\n"));
    protected void PushIndent() => _indent += "\t";
    protected void PopIndent() => _indent = _indent[1..];
    private string GetStringFromMemoryStream() => Encoding.UTF8.GetString(_stream.ToArray());
}