namespace Loom.Syntax;

public enum SyntaxKind : ushort
{
    Whitespace,
    Semicolon,
    Comment,
    
    Plus,
    PlusEquals,
    Minus,
    MinusEquals,
    Star,
    StarEquals,
    Slash,
    SlashEquals,
    Percent,
    PercentEquals,
    Carat,
    CaratEquals,
    Ampersand,
    AmpersandEquals,
    Pipe,
    PipeEquals,
    AmpersandAmpersand,
    AmpersandAmpersandEquals,
    PipePipe,
    PipePipeEquals,
    Colon,
    Bang,
    Equals,
    EqualsEquals,
    BangEquals,
    LArrow,
    LArrowEquals,
    RArrow,
    RArrowEquals,
    LArrowLArrow,
    LArrowLArrowEquals,
    RArrowRArrow,
    RArrowRArrowEquals,
    RArrowRArrowRArrow,
    RArrowRArrowRArrowEquals,
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    
    IntegerLiteral,
    FloatLiteral
}