namespace Loom.Syntax;

public enum SyntaxKind : ushort
{
    Whitespace,
    Semicolon,
    Comment,

    Plus,
    PlusEquals,
    Minus,
    MinusEquals,
    Star,
    StarEquals,
    Slash,
    SlashEquals,
    SlashSlash,
    SlashSlashEquals,
    Percent,
    PercentEquals,
    Carat,
    CaratEquals,
    Ampersand,
    AmpersandEquals,
    Pipe,
    PipeEquals,
    Tilde,
    TildeEquals,
    AmpersandAmpersand,
    AmpersandAmpersandEquals,
    PipePipe,
    PipePipeEquals,
    Colon,
    Question,
    QuestionQuestion,
    QuestionQuestionEquals,
    Bang,
    Equals,
    EqualsEquals,
    BangEquals,
    LArrow,
    LArrowEquals,
    RArrow,
    RArrowEquals,
    LArrowLArrow,
    LArrowLArrowEquals,
    RArrowRArrow,
    RArrowRArrowEquals,
    RArrowRArrowRArrow,
    RArrowRArrowRArrowEquals,
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,

    IntegerLiteral,
    FloatLiteral,
    StringLiteral,
    TrueLiteral,
    FalseLiteral,
    NoneLiteral,

    LetKeyword,
    MutKeyword,
    FnKeyword,

    Identifier
}