using Loom.Syntax;

namespace Loom.Lexing;

using static LexerRule;
using static SyntaxKind;

public static class LexerRules
{
    public static readonly List<LexerRule> Standard =
    [
        SingleCharacter(Plus, '+'),
        MultiCharacter(PlusEquals, "+="),
        SingleCharacter(Minus, '-'),
        MultiCharacter(MinusEquals, "-="),
        SingleCharacter(Star, '*'),
        MultiCharacter(StarEquals, "*="),
        SingleCharacter(Slash, '/'),
        MultiCharacter(SlashEquals, "/="),
        MultiCharacter(SlashSlash, "//"),
        MultiCharacter(SlashSlashEquals, "//="),
        SingleCharacter(Percent, '%'),
        MultiCharacter(PercentEquals, "%="),
        SingleCharacter(Carat, '^'),
        MultiCharacter(CaratEquals, "^="),
        SingleCharacter(Ampersand, '&'),
        MultiCharacter(AmpersandEquals, "&="),
        MultiCharacter(AmpersandAmpersand, "&&"),
        MultiCharacter(AmpersandAmpersandEquals, "&&="),
        SingleCharacter(Pipe, '|'),
        MultiCharacter(PipeEquals, "|="),
        SingleCharacter(Tilde, '~'),
        MultiCharacter(TildeEquals, "~="),
        MultiCharacter(PipePipe, "||"),
        MultiCharacter(PipePipeEquals, "||="),
        SingleCharacter(Colon, ':'),
        SingleCharacter(Question, '?'),
        MultiCharacter(QuestionQuestion, "??"),
        MultiCharacter(QuestionQuestionEquals, "??="),
        SingleCharacter(Bang, '!'),
        MultiCharacter(BangEquals, "!="),
        SingleCharacter(SyntaxKind.Equals, '='),
        MultiCharacter(EqualsEquals, "=="),
        SingleCharacter(LArrow, '<'),
        MultiCharacter(LArrowLArrow, "<<"),
        MultiCharacter(LArrowLArrowEquals, "<<="),
        MultiCharacter(LArrowEquals, "<="),
        SingleCharacter(RArrow, '>'),
        MultiCharacter(RArrowRArrow, ">>"),
        MultiCharacter(RArrowRArrowEquals, ">>="),
        MultiCharacter(RArrowRArrowRArrow, ">>>"),
        MultiCharacter(RArrowRArrowRArrowEquals, ">>>="),
        MultiCharacter(RArrowEquals, ">="),
        SingleCharacter(LParen, '('),
        SingleCharacter(RParen, ')'),
        SingleCharacter(LBracket, '['),
        SingleCharacter(RBracket, ']'),
        SingleCharacter(LBrace, '{'),
        SingleCharacter(RBrace, '}'),
        SingleCharacter(Comma, ','),
        SingleCharacter(Dot, '.'),
        MultiCharacter(DotDot, ".."),
        RegEx(IntegerLiteral, @"\d+"),
        RegEx(FloatLiteral, @"(\d+\.\d+|\.\d+|\d+\.\d+)"),
        RegEx(StringLiteral, "\".*\"|'.*'"),
        MultiCharacter(TrueLiteral, "true"),
        MultiCharacter(FalseLiteral, "false"),
        MultiCharacter(NoneLiteral, "none"),
        MultiCharacter(LetKeyword, "let"),
        MultiCharacter(MutKeyword, "mut"),
        MultiCharacter(TypeKeyword, "type"),
        MultiCharacter(InterfaceKeyword, "interface"),
        MultiCharacter(FnKeyword, "fn"),
        MultiCharacter(FnKeyword, "fn"),
        MultiCharacter(EventKeyword, "event"),
        MultiCharacter(EnumKeyword, "enum"),
        MultiCharacter(EveryKeyword, "every"),
        MultiCharacter(AfterKeyword, "after"),
        MultiCharacter(IfKeyword, "if"),
        MultiCharacter(ElseKeyword, "else"),
        MultiCharacter(WhileKeyword, "while"),
        MultiCharacter(MatchKeyword, "match"),
        MultiCharacter(NameofKeyword, "nameof"),
        RegEx(Identifier, "[a-zA-Z_]([a-zA-Z0-9_]*)"),
        SingleCharacter(Semicolon, ';'),
        RegEx(Whitespace, @"\s+")
    ];
}